######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 21 13:25:29 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../../

CONFIG += static

QT += webkit opengl network

!mac {
unix {
    DEFINES += LL_LINUX
#    DEFINES += LL_LINUX LL_NEWER_GLUI
    LIBS += -lglui -lglut
    LIBS += $$PWD/../../libllmozlib2.a
}
}

mac {
    DEFINES += LL_OSX
    LIBS += -framework GLUT -framework OpenGL
}


win32{
    DEFINES += _WINDOWS
    INCLUDEPATH += ../
    LIBS += -L../GL $$PWD/../../Debug/llmozlib2.lib
    DESTDIR=../GL
}

QTPLUGIN += qgif
# Input
SOURCES += testgl.cpp
